/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: dfnze324 (https://sketchfab.com/dfnze324)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/explosion-c90b52d4d4254deb861ad0473566885d
title: explosion
*/

import React, { useRef, useState, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/explosion/scene.gltf');
  const { actions } = useAnimations(animations, group);

  const [name, setName] = useState("Take_001");


  useFrame(() => {
    //actions[name].play();
  });





  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group>
              <group>
                <group>
                  <group position={[-3.22, 4.82, 0.95]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_0_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_0_lambert1_0.material} />
                  </group>
                  <group position={[1.47, 6.22, 1.75]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_1_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_1_lambert1_0.material} />
                  </group>
                  <group position={[1.97, 1.41, -2.55]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_2_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_2_lambert1_0.material} />
                  </group>
                  <group position={[-0.6, 4.17, 3.62]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_3_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_3_lambert1_0.material} />
                  </group>
                  <group position={[3.13, 1.15, -0.27]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_4_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_4_lambert1_0.material} />
                  </group>
                  <group position={[-1.54, 4.47, 3.28]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_5_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_5_lambert1_0.material} />
                  </group>
                  <group position={[3.06, 3.47, -2.33]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_6_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_6_lambert1_0.material} />
                  </group>
                  <group position={[-2.59, 0.84, 1.49]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_7_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_7_lambert1_0.material} />
                  </group>
                  <group position={[-1.94, 5.6, 2.44]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_8_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_8_lambert1_0.material} />
                  </group>
                  <group position={[1.43, 6.82, 0.94]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_9_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_9_lambert1_0.material} />
                  </group>
                  <group position={[2.46, 6.08, 1.3]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_10_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_10_lambert1_0.material} />
                  </group>
                  <group position={[2.44, 1.03, 2.2]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_11_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_11_lambert1_0.material} />
                  </group>
                  <group position={[-2.94, 5.67, -1.29]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_12_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_12_lambert1_0.material} />
                  </group>
                  <group position={[2.15, 6.49, 1.21]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_13_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_13_lambert1_0.material} />
                  </group>
                  <group position={[0.7, 6.52, -2.37]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_14_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_14_lambert1_0.material} />
                  </group>
                  <group position={[2.06, 4.17, 2.21]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_15_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_15_lambert1_0.material} />
                  </group>
                  <group position={[-1.86, 3.16, -2.53]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_16_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_16_lambert1_0.material} />
                  </group>
                  <group position={[2.24, 1.66, -1.48]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_17_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_17_lambert1_0.material} />
                  </group>
                  <group position={[-2.34, 3.78, 2.14]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_18_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_18_lambert1_0.material} />
                  </group>
                  <group position={[2.63, 1.51, -0.29]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_19_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_19_lambert1_0.material} />
                  </group>
                  <group position={[1.53, 0.95, 1.57]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_20_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_20_lambert1_0.material} />
                  </group>
                  <group position={[1.29, 0.91, -1.77]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_21_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_21_lambert1_0.material} />
                  </group>
                  <group position={[-0.49, 6.29, 1.5]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_22_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_22_lambert1_0.material} />
                  </group>
                  <group position={[2.87, 3.49, 1.71]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_23_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_23_lambert1_0.material} />
                  </group>
                  <group position={[-1.9, 5.56, -1.72]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_24_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_24_lambert1_0.material} />
                  </group>
                  <group position={[-2.79, 3.51, 1.94]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_25_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_25_lambert1_0.material} />
                  </group>
                  <group position={[0.29, 6.19, -1.9]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_26_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_26_lambert1_0.material} />
                  </group>
                  <group position={[2.4, 1.34, 1.41]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_27_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_27_lambert1_0.material} />
                  </group>
                  <group position={[2.15, 5.2, 2]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_28_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_28_lambert1_0.material} />
                  </group>
                  <group position={[2.05, 4.81, -2.45]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_29_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_29_lambert1_0.material} />
                  </group>
                  <group position={[2.55, 5.71, 0.59]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_30_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_30_lambert1_0.material} />
                  </group>
                  <group position={[-0.82, 1.44, 1.42]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_31_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_31_lambert1_0.material} />
                  </group>
                  <group position={[-0.56, 2.82, 2.47]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_32_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_32_lambert1_0.material} />
                  </group>
                  <group position={[-1.63, 2.06, -1.55]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_33_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_33_lambert1_0.material} />
                  </group>
                  <group position={[0.59, 5.42, -1.65]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_34_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_34_lambert1_0.material} />
                  </group>
                  <group position={[-0.99, 5.75, -0.87]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_35_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_35_lambert1_0.material} />
                  </group>
                  <group position={[-1.62, 5.58, -0.36]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_36_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_36_lambert1_0.material} />
                  </group>
                  <group position={[-1.49, 5.5, -0.96]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_37_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_37_lambert1_0.material} />
                  </group>
                  <group position={[-1.84, 1.42, 0.37]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_38_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_38_lambert1_0.material} />
                  </group>
                  <group position={[1.81, 5.46, -0.52]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_39_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_39_lambert1_0.material} />
                  </group>
                  <group position={[1.41, 1, 0.2]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_40_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_40_lambert1_0.material} />
                  </group>
                  <group position={[-1.82, 1.67, -1.27]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_41_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_41_lambert1_0.material} />
                  </group>
                  <group position={[-1.86, 1.28, 0.29]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_42_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_42_lambert1_0.material} />
                  </group>
                  <group position={[-2.66, 2.33, 0.21]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_43_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_43_lambert1_0.material} />
                  </group>
                  <group position={[-1.01, 0.75, -0.51]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_44_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_44_lambert1_0.material} />
                  </group>
                  <group position={[-0.59, 5.84, -1.58]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_45_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_45_lambert1_0.material} />
                  </group>
                  <group position={[0.99, 5.21, -2.16]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_46_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_46_lambert1_0.material} />
                  </group>
                  <group position={[1.52, 4.06, -1.17]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_47_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_47_lambert1_0.material} />
                  </group>
                  <group position={[1.07, 4.26, -1.54]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_48_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_48_lambert1_0.material} />
                  </group>
                  <group position={[0.63, 1.61, 0.56]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_49_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_49_lambert1_0.material} />
                  </group>
                  <group position={[-1.99, 3.52, 0.57]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_50_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_50_lambert1_0.material} />
                  </group>
                  <group position={[-0.27, 4.89, -1.55]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_51_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_51_lambert1_0.material} />
                  </group>
                  <group position={[-2.1, 3.57, 0.28]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_52_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_52_lambert1_0.material} />
                  </group>
                  <group position={[0.12, 5.16, 1.36]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_53_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_53_lambert1_0.material} />
                  </group>
                  <group position={[1.55, 4.06, 1.43]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_54_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_54_lambert1_0.material} />
                  </group>
                  <group position={[-0.41, 4.94, -1.61]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_55_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_55_lambert1_0.material} />
                  </group>
                  <group position={[0.74, 5.34, 0.95]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_56_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_56_lambert1_0.material} />
                  </group>
                  <group position={[1.72, 3.18, -1.41]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_57_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_57_lambert1_0.material} />
                  </group>
                  <group position={[0.1, 3.76, 2.26]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_58_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_58_lambert1_0.material} />
                  </group>
                  <group position={[-1.2, 4.78, -1.48]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_59_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_59_lambert1_0.material} />
                  </group>
                  <group position={[-0.88, 5.48, -0.83]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_60_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_60_lambert1_0.material} />
                  </group>
                  <group position={[-2.01, 2.58, 0.88]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_61_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_61_lambert1_0.material} />
                  </group>
                  <group position={[-0.99, 4.63, 1.86]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_62_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_62_lambert1_0.material} />
                  </group>
                  <group position={[-0.5, 4.74, -0.52]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_63_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_63_lambert1_0.material} />
                  </group>
                  <group position={[0.94, 3.04, -0.99]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_64_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_64_lambert1_0.material} />
                  </group>
                  <group position={[0.86, 4.6, -0.52]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_65_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_65_lambert1_0.material} />
                  </group>
                  <group position={[-0.94, 2.4, -0.12]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_66_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_66_lambert1_0.material} />
                  </group>
                  <group position={[1, 4.31, -0.83]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_67_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_67_lambert1_0.material} />
                  </group>
                  <group position={[0.48, 2.81, 1.27]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_68_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_68_lambert1_0.material} />
                  </group>
                  <group position={[0.87, 2.73, -1.04]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_69_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_69_lambert1_0.material} />
                  </group>
                  <group position={[-0.97, 4.61, 0.67]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_70_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_70_lambert1_0.material} />
                  </group>
                  <group position={[0.79, 4.72, 0.74]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_71_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_71_lambert1_0.material} />
                  </group>
                  <group position={[1.26, 4.02, 0.92]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_72_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_72_lambert1_0.material} />
                  </group>
                  <group position={[0.81, 2.85, -1.3]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_73_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_73_lambert1_0.material} />
                  </group>
                  <group position={[0.73, 2.31, 0.94]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_74_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_74_lambert1_0.material} />
                  </group>
                  <group position={[1.54, 3.7, 0.78]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_75_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_75_lambert1_0.material} />
                  </group>
                  <group position={[0.05, 5.14, 0.71]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_76_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_76_lambert1_0.material} />
                  </group>
                  <group position={[-1.5, 4.42, 0.23]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_77_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_77_lambert1_0.material} />
                  </group>
                  <group position={[-1.39, 2.37, -0.12]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_78_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_78_lambert1_0.material} />
                  </group>
                  <group position={[-0.69, 3.92, -0.23]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_79_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_79_lambert1_0.material} />
                  </group>
                  <group position={[-0.2, 3.55, -0.82]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_80_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_80_lambert1_0.material} />
                  </group>
                  <group position={[-0.48, 3.2, 0.62]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_81_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_81_lambert1_0.material} />
                  </group>
                  <group position={[0.54, 3.64, 0.69]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_82_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_82_lambert1_0.material} />
                  </group>
                  <group position={[-0.66, 4.16, -0.18]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_83_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_83_lambert1_0.material} />
                  </group>
                  <group position={[0.44, 3.61, -0.82]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_84_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_84_lambert1_0.material} />
                  </group>
                  <group position={[-0.14, 3.85, 0.93]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_85_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_85_lambert1_0.material} />
                  </group>
                  <group position={[0.51, 3.03, 0.67]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_86_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_86_lambert1_0.material} />
                  </group>
                  <group position={[-0.64, 3.7, -0.78]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_87_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_87_lambert1_0.material} />
                  </group>
                  <group position={[-0.4, 2.81, -0.61]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_88_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_88_lambert1_0.material} />
                  </group>
                  <group position={[-0.81, 4.12, -0.44]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_89_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_89_lambert1_0.material} />
                  </group>
                  <group position={[0.41, 2.56, -0.2]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_90_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_90_lambert1_0.material} />
                  </group>
                  <group position={[-0.12, 4.46, 0.66]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_91_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_91_lambert1_0.material} />
                  </group>
                  <group position={[-0.66, 3.49, -0.93]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_92_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_92_lambert1_0.material} />
                  </group>
                  <group position={[0.82, 2.75, 0.31]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_93_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_93_lambert1_0.material} />
                  </group>
                  <group position={[0.05, 2.89, 1]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_94_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_94_lambert1_0.material} />
                  </group>
                  <group position={[-0.15, 3.71, -0.02]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_95_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_95_lambert1_0.material} />
                  </group>
                  <group position={[-0.05, 3.82, -0.03]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_96_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_96_lambert1_0.material} />
                  </group>
                  <group position={[0.02, 3.33, -0.1]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_97_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_97_lambert1_0.material} />
                  </group>
                  <group position={[0.1, 3.33, -0.15]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_98_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_98_lambert1_0.material} />
                  </group>
                  <group position={[0.06, 3.81, 0.19]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_99_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_99_lambert1_0.material} />
                  </group>
                  <group position={[0.15, 3.56, 0.31]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_100_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_100_lambert1_0.material} />
                  </group>
                  <group position={[-0.25, 3.3, 0.02]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_101_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_101_lambert1_0.material} />
                  </group>
                  <group position={[0.24, 3.34, -0.19]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_102_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_102_lambert1_0.material} />
                  </group>
                  <group position={[0.08, 3.77, -0.37]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_103_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_103_lambert1_0.material} />
                  </group>
                  <group position={[0.27, 3.33, 0.26]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_104_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_104_lambert1_0.material} />
                  </group>
                  <group position={[-0.32, 3.51, -0.34]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_105_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_105_lambert1_0.material} />
                  </group>
                  <group position={[0.42, 3.82, -0.07]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_106_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_106_lambert1_0.material} />
                  </group>
                  <group position={[0.38, 3.92, -0.11]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_107_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_107_lambert1_0.material} />
                  </group>
                  <group position={[-0.04, 3.88, -0.45]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_108_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_108_lambert1_0.material} />
                  </group>
                  <group position={[0.3, 3.98, -0.29]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_109_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_109_lambert1_0.material} />
                  </group>
                  <group position={[-0.45, 3.95, 0.15]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_110_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_110_lambert1_0.material} />
                  </group>
                  <group position={[8.85, 3.1, -8.03]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_111_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_111_lambert1_0.material} />
                  </group>
                  <group position={[-2.55, 10.61, -6.4]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_112_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_112_lambert1_0.material} />
                  </group>
                  <group position={[-2.79, 11.97, -3.11]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_113_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_113_lambert1_0.material} />
                  </group>
                  <group position={[-8.87, -1.66, -8.03]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_114_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_114_lambert1_0.material} />
                  </group>
                  <group position={[-9.28, -7.28, 0]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_115_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_115_lambert1_0.material} />
                  </group>
                  <group position={[7.88, 8.58, -4.44]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_116_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_116_lambert1_0.material} />
                  </group>
                  <group position={[4.59, 2.95, -10.9]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_117_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_117_lambert1_0.material} />
                  </group>
                  <group position={[0.1, 7.65, -9.71]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_118_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_118_lambert1_0.material} />
                  </group>
                  <group position={[-5.89, 9.55, -5.33]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_119_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_119_lambert1_0.material} />
                  </group>
                  <group position={[8.8, -4.66, 6.3]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_120_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_120_lambert1_0.material} />
                  </group>
                  <group position={[7.38, 9.93, -0.4]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_121_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_121_lambert1_0.material} />
                  </group>
                  <group position={[7.97, 9.29, -1.51]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_122_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_122_lambert1_0.material} />
                  </group>
                  <group position={[1, -10.93, 3.11]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_123_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_123_lambert1_0.material} />
                  </group>
                  <group position={[6.97, 7.58, -6.56]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_124_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_124_lambert1_0.material} />
                  </group>
                  <group position={[8.12, 0.93, 8.63]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_125_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_125_lambert1_0.material} />
                  </group>
                  <group position={[7.98, -3.59, -7.71]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_126_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_126_lambert1_0.material} />
                  </group>
                  <group position={[-0.85, -8.64, 7.09]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_127_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_127_lambert1_0.material} />
                  </group>
                  <group position={[-8.98, 7.61, -3.43]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_128_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_128_lambert1_0.material} />
                  </group>
                  <group position={[10.86, -3.68, 0.95]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_129_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_129_lambert1_0.material} />
                  </group>
                  <group position={[9.22, -0.12, 7.18]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_130_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_130_lambert1_0.material} />
                  </group>
                  <group position={[-5.27, 5.57, -9.3]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_131_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_131_lambert1_0.material} />
                  </group>
                  <group position={[3.24, 8.42, 8.19]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_132_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_132_lambert1_0.material} />
                  </group>
                  <group position={[6.3, 1.84, -9.76]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_133_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_133_lambert1_0.material} />
                  </group>
                  <group position={[-11.12, -0.99, 2.91]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_134_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_134_lambert1_0.material} />
                  </group>
                  <group position={[1.91, -6.03, -9.21]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_135_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_135_lambert1_0.material} />
                  </group>
                  <group position={[-8.54, -6.75, 2.12]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_136_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_136_lambert1_0.material} />
                  </group>
                  <group position={[6.34, -8.47, 2.86]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_137_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_137_lambert1_0.material} />
                  </group>
                  <group position={[-0.66, -8.87, -6.28]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_138_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_138_lambert1_0.material} />
                  </group>
                  <group position={[8.3, 3.55, 7.48]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_139_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_139_lambert1_0.material} />
                  </group>
                  <group position={[2.09, -5.87, 9.13]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_140_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_140_lambert1_0.material} />
                  </group>
                  <group position={[-3.53, -7.85, -6.64]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_141_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_141_lambert1_0.material} />
                  </group>
                  <group position={[-1.91, -1.25, 11.08]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_142_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_142_lambert1_0.material} />
                  </group>
                  <group position={[-5.2, -6.2, -7.14]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_143_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_143_lambert1_0.material} />
                  </group>
                  <group position={[5.62, 7.27, 7.63]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_144_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_144_lambert1_0.material} />
                  </group>
                  <group position={[6.74, -3.34, -8.01]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_145_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_145_lambert1_0.material} />
                  </group>
                  <group position={[-8.34, 6.8, -4.96]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_146_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_146_lambert1_0.material} />
                  </group>
                  <group position={[0.89, -10.25, -0.53]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_147_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_147_lambert1_0.material} />
                  </group>
                  <group position={[3.27, 9.93, -6.01]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_148_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_148_lambert1_0.material} />
                  </group>
                  <group position={[4.77, -5.41, 7.9]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_149_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_149_lambert1_0.material} />
                  </group>
                  <group position={[2.35, 4.41, -10.42]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_150_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_150_lambert1_0.material} />
                  </group>
                  <group position={[6.3, 8.15, 5.86]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_151_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_151_lambert1_0.material} />
                  </group>
                  <group position={[9.4, 6.98, -0.35]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_152_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_152_lambert1_0.material} />
                  </group>
                  <group position={[8.93, -5.64, -0.48]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_153_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_153_lambert1_0.material} />
                  </group>
                  <group position={[5.89, 8.82, -5.21]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_154_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_154_lambert1_0.material} />
                  </group>
                  <group position={[-8.18, -5.23, 4.12]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_155_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_155_lambert1_0.material} />
                  </group>
                  <group position={[7.59, 4.31, 7.31]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_156_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_156_lambert1_0.material} />
                  </group>
                  <group position={[-8.16, -1.97, 6.78]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_157_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_157_lambert1_0.material} />
                  </group>
                  <group position={[-7.15, -1.31, -8.05]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_158_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_158_lambert1_0.material} />
                  </group>
                  <group position={[-2.84, -5, -8.56]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_159_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_159_lambert1_0.material} />
                  </group>
                  <group position={[-3.68, 11.42, 1.2]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_160_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_160_lambert1_0.material} />
                  </group>
                  <group position={[5.42, 2.29, -9.4]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_161_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_161_lambert1_0.material} />
                  </group>
                  <group position={[-9.16, 4.81, 4.61]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_162_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_162_lambert1_0.material} />
                  </group>
                  <group position={[0.22, -5.8, -8.29]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_163_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_163_lambert1_0.material} />
                  </group>
                  <group position={[6.27, 9.33, -3.48]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_164_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_164_lambert1_0.material} />
                  </group>
                  <group position={[-4.46, -8.51, -1.46]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_165_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_165_lambert1_0.material} />
                  </group>
                  <group position={[-2.14, -3.15, -9.61]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_166_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_166_lambert1_0.material} />
                  </group>
                  <group position={[5.12, -4.53, 7.53]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_167_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_167_lambert1_0.material} />
                  </group>
                  <group position={[-9.45, -2.35, 3.62]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_168_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_168_lambert1_0.material} />
                  </group>
                  <group position={[-10.59, -0.12, 0.72]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_169_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_169_lambert1_0.material} />
                  </group>
                  <group position={[-6.3, -7.34, -1.02]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_170_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_170_lambert1_0.material} />
                  </group>
                  <group position={[-5.51, 9.67, -3.36]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_171_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_171_lambert1_0.material} />
                  </group>
                  <group position={[-2.79, -7.89, 4.74]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_172_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_172_lambert1_0.material} />
                  </group>
                  <group position={[-3.86, -8.6, 0.99]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_173_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_173_lambert1_0.material} />
                  </group>
                  <group position={[0.5, 9.86, 6.03]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_174_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_174_lambert1_0.material} />
                  </group>
                  <group position={[-6.18, 7.43, 5.99]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_175_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_175_lambert1_0.material} />
                  </group>
                  <group position={[-5.47, -4.98, 6.27]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_176_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_176_lambert1_0.material} />
                  </group>
                  <group position={[5.66, 2.21, -8.77]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_177_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_177_lambert1_0.material} />
                  </group>
                  <group position={[-7.12, -1.19, 7.18]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_178_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_178_lambert1_0.material} />
                  </group>
                  <group position={[-6.71, -2.35, 7.02]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_179_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_179_lambert1_0.material} />
                  </group>
                  <group position={[-8.43, -4.62, 0.52]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_180_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_180_lambert1_0.material} />
                  </group>
                  <group position={[4.05, 10.89, -0.9]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_181_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_181_lambert1_0.material} />
                  </group>
                  <group position={[4.06, 10.6, 2.41]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_182_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_182_lambert1_0.material} />
                  </group>
                  <group position={[-8, 7.81, -0.99]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_183_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_183_lambert1_0.material} />
                  </group>
                  <group position={[-6.23, -0.93, 7.83]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_184_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_184_lambert1_0.material} />
                  </group>
                  <group position={[0.93, 6.06, -9.09]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_185_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_185_lambert1_0.material} />
                  </group>
                  <group position={[-9.39, 4.29, -2.81]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_186_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_186_lambert1_0.material} />
                  </group>
                  <group position={[-4.71, 8.2, 5.95]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_187_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_187_lambert1_0.material} />
                  </group>
                  <group position={[-3.36, 10.87, -1.66]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_188_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_188_lambert1_0.material} />
                  </group>
                  <group position={[-2.27, -3.43, -8.62]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_189_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_189_lambert1_0.material} />
                  </group>
                  <group position={[1.51, -6.6, 5.64]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_190_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_190_lambert1_0.material} />
                  </group>
                  <group position={[7.09, -2.81, 5.59]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_191_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_191_lambert1_0.material} />
                  </group>
                  <group position={[5.34, -6.32, -2.95]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_192_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_192_lambert1_0.material} />
                  </group>
                  <group position={[-3.03, 1.9, 9.51]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_193_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_193_lambert1_0.material} />
                  </group>
                  <group position={[-9.02, -0.36, -3.74]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_194_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_194_lambert1_0.material} />
                  </group>
                  <group position={[-8.39, 0.06, -5.11]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_195_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_195_lambert1_0.material} />
                  </group>
                  <group position={[-6.63, 2.79, 7.28]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_196_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_196_lambert1_0.material} />
                  </group>
                  <group position={[0.5, 11.23, -2.22]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_197_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_197_lambert1_0.material} />
                  </group>
                  <group position={[0.97, 11.44, 0.08]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_198_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_198_lambert1_0.material} />
                  </group>
                  <group position={[8.7, 5.77, 1.92]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_199_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_199_lambert1_0.material} />
                  </group>
                  <group position={[1.68, 8, 7.27]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_200_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_200_lambert1_0.material} />
                  </group>
                  <group position={[-1.05, -1.55, 9.19]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_201_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_201_lambert1_0.material} />
                  </group>
                  <group position={[-1.21, -2.68, 8.67]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_202_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_202_lambert1_0.material} />
                  </group>
                  <group position={[-5.95, -5.7, 2.36]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_203_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_203_lambert1_0.material} />
                  </group>
                  <group position={[-4.3, 3.99, 8.37]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_204_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_204_lambert1_0.material} />
                  </group>
                  <group position={[6.66, 5.32, -5.98]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_205_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_205_lambert1_0.material} />
                  </group>
                  <group position={[-8.33, 6.29, -1.76]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_206_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_206_lambert1_0.material} />
                  </group>
                  <group position={[-1.73, -5.25, -6.24]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_207_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_207_lambert1_0.material} />
                  </group>
                  <group position={[-5.2, -5.38, 3.55]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_208_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_208_lambert1_0.material} />
                  </group>
                  <group position={[0.7, -4.16, -7.42]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_209_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_209_lambert1_0.material} />
                  </group>
                  <group position={[2.9, 8.33, -6.26]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_210_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_210_lambert1_0.material} />
                  </group>
                  <group position={[9.13, 3.33, 2.12]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_211_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_211_lambert1_0.material} />
                  </group>
                  <group position={[1.12, 3.53, 9.22]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_212_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_212_lambert1_0.material} />
                  </group>
                  <group position={[-5.76, -1.46, 6.71]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_213_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_213_lambert1_0.material} />
                  </group>
                  <group position={[-3.4, 8.72, -5.38]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_214_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_214_lambert1_0.material} />
                  </group>
                  <group position={[-6, 4.14, -6.83]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_215_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_215_lambert1_0.material} />
                  </group>
                  <group position={[-8.81, 0.86, 2.98]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_216_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_216_lambert1_0.material} />
                  </group>
                  <group position={[-3.94, 6.41, -7.1]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_217_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_217_lambert1_0.material} />
                  </group>
                  <group position={[-4.48, -5.62, 3.36]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_218_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_218_lambert1_0.material} />
                  </group>
                  <group position={[-5.85, 3.77, -6.92]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_219_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_219_lambert1_0.material} />
                  </group>
                  <group position={[0.57, -7.25, 1.82]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_220_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_220_lambert1_0.material} />
                  </group>
                  <group position={[3.43, -5.64, 4.24]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_221_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_221_lambert1_0.material} />
                  </group>
                  <group position={[0.71, -3.31, 7.43]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_222_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_222_lambert1_0.material} />
                  </group>
                  <group position={[-3.8, -4.53, 5.15]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_223_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_223_lambert1_0.material} />
                  </group>
                  <group position={[-7.59, 1.1, 4.93]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_224_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_224_lambert1_0.material} />
                  </group>
                  <group position={[-4.33, 3.73, -7.77]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_225_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_225_lambert1_0.material} />
                  </group>
                  <group position={[-6.41, -0.29, -5.96]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_226_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_226_lambert1_0.material} />
                  </group>
                  <group position={[4.95, 7.01, -5.64]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_227_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_227_lambert1_0.material} />
                  </group>
                  <group position={[4.91, 2.63, -7.53]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_228_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_228_lambert1_0.material} />
                  </group>
                  <group position={[-5.59, 8.22, 3.21]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_229_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_229_lambert1_0.material} />
                  </group>
                  <group position={[7.2, 6.23, -3.19]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_230_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_230_lambert1_0.material} />
                  </group>
                  <group position={[6.27, 3.89, 6.05]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_231_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_231_lambert1_0.material} />
                  </group>
                  <group position={[-0.75, -3.61, 6.88]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_232_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_232_lambert1_0.material} />
                  </group>
                  <group position={[-7.06, 5.13, 4.34]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_233_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_233_lambert1_0.material} />
                  </group>
                  <group position={[5.35, -4.32, -3.14]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_234_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_234_lambert1_0.material} />
                  </group>
                  <group position={[1.69, -3.94, 6.32]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_235_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_235_lambert1_0.material} />
                  </group>
                  <group position={[3.47, 6.24, -6.87]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_236_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_236_lambert1_0.material} />
                  </group>
                  <group position={[2.02, -4.72, -5.26]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_237_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_237_lambert1_0.material} />
                  </group>
                  <group position={[8.21, 2.26, 2.8]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_238_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_238_lambert1_0.material} />
                  </group>
                  <group position={[-6.44, 7.83, 1.21]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_239_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_239_lambert1_0.material} />
                  </group>
                  <group position={[0.81, 1.55, -8.57]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_240_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_240_lambert1_0.material} />
                  </group>
                  <group position={[-6.23, -1.88, 4.35]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_241_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_241_lambert1_0.material} />
                  </group>
                  <group position={[2.02, -2.95, 6.6]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_242_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_242_lambert1_0.material} />
                  </group>
                  <group position={[5.84, 4.39, -5.82]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_243_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_243_lambert1_0.material} />
                  </group>
                  <group position={[2.75, -0.45, -7.63]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_244_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_244_lambert1_0.material} />
                  </group>
                  <group position={[-4.58, -3.07, -4.91]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_245_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_245_lambert1_0.material} />
                  </group>
                  <group position={[7.74, -0.82, 1.73]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_246_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_246_lambert1_0.material} />
                  </group>
                  <group position={[-4.05, -4.55, -3.19]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_247_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_247_lambert1_0.material} />
                  </group>
                  <group position={[-6.94, 6.72, -1.32]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_248_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_248_lambert1_0.material} />
                  </group>
                  <group position={[2.04, 8.35, 5.28]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_249_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_249_lambert1_0.material} />
                  </group>
                  <group position={[4.27, -3.22, -4.76]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_250_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_250_lambert1_0.material} />
                  </group>
                  <group position={[-0.13, 9.78, 3.44]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_251_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_251_lambert1_0.material} />
                  </group>
                  <group position={[6.29, 7.05, -2.44]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_252_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_252_lambert1_0.material} />
                  </group>
                  <group position={[3.45, 8.25, -4.45]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_253_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_253_lambert1_0.material} />
                  </group>
                  <group position={[-6.33, 1.77, -5.18]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_254_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_254_lambert1_0.material} />
                  </group>
                  <group position={[-6.33, 4.67, -4.59]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_255_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_255_lambert1_0.material} />
                  </group>
                  <group position={[2.44, 9.67, -2.59]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_256_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_256_lambert1_0.material} />
                  </group>
                  <group position={[0.82, 10.19, -1.87]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_257_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_257_lambert1_0.material} />
                  </group>
                  <group position={[-6.02, 3.67, -5.24]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_258_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_258_lambert1_0.material} />
                  </group>
                  <group position={[4.65, 8.29, -2.81]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_259_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_259_lambert1_0.material} />
                  </group>
                  <group position={[5.22, 5.76, -5.08]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_260_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_260_lambert1_0.material} />
                  </group>
                  <group position={[-2.7, -3.51, 4.8]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_261_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_261_lambert1_0.material} />
                  </group>
                  <group position={[-7.3, -0.19, 2.11]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_262_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_262_lambert1_0.material} />
                  </group>
                  <group position={[-1.02, -2.58, 6.21]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_263_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_263_lambert1_0.material} />
                  </group>
                  <group position={[-0.71, -5.59, 0.24]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_264_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_264_lambert1_0.material} />
                  </group>
                  <group position={[-5.64, 3.34, 5.48]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_265_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_265_lambert1_0.material} />
                  </group>
                  <group position={[2.37, 1.31, -7.45]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_266_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_266_lambert1_0.material} />
                  </group>
                  <group position={[1.56, 7.54, -5.68]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_267_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_267_lambert1_0.material} />
                  </group>
                  <group position={[2.25, -1.99, -6.16]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_268_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_268_lambert1_0.material} />
                  </group>
                  <group position={[-1.57, -4.85, 2.7]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_269_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_269_lambert1_0.material} />
                  </group>
                  <group position={[-3.38, 6.86, -5.39]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_270_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_270_lambert1_0.material} />
                  </group>
                  <group position={[5.9, 6.54, 2.79]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_271_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_271_lambert1_0.material} />
                  </group>
                  <group position={[-3.96, 5.42, -5.89]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_272_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_272_lambert1_0.material} />
                  </group>
                  <group position={[-7.63, 2.23, 0.1]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_273_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_273_lambert1_0.material} />
                  </group>
                  <group position={[-3.46, 4.36, 6.51]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_274_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_274_lambert1_0.material} />
                  </group>
                  <group position={[-0.54, 4.51, -7.31]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_275_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_275_lambert1_0.material} />
                  </group>
                  <group position={[5.86, 5.49, 3.71]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_276_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_276_lambert1_0.material} />
                  </group>
                  <group position={[-2.16, -4.57, -1.57]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_277_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_277_lambert1_0.material} />
                  </group>
                  <group position={[6.95, 0.68, 2.18]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_278_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_278_lambert1_0.material} />
                  </group>
                  <group position={[7.12, 0.23, 0.35]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_279_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_279_lambert1_0.material} />
                  </group>
                  <group position={[-2.73, 4.42, 6.65]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_280_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_280_lambert1_0.material} />
                  </group>
                  <group position={[-7.27, 3.6, 1.13]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_281_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_281_lambert1_0.material} />
                  </group>
                  <group position={[-3.51, 5.91, 5.54]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_282_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_282_lambert1_0.material} />
                  </group>
                  <group position={[2.9, -3.72, 2.74]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_283_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_283_lambert1_0.material} />
                  </group>
                  <group position={[3.34, -2.15, 4.63]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_284_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_284_lambert1_0.material} />
                  </group>
                  <group position={[-4.42, -2.43, 3.19]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_285_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_285_lambert1_0.material} />
                  </group>
                  <group position={[3.49, -2.66, -3.51]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_286_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_286_lambert1_0.material} />
                  </group>
                  <group position={[-2.73, 2.01, 6.62]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_287_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_287_lambert1_0.material} />
                  </group>
                  <group position={[0.62, 7.22, -5.47]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_288_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_288_lambert1_0.material} />
                  </group>
                  <group position={[-3.21, -2.88, -3.24]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_289_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_289_lambert1_0.material} />
                  </group>
                  <group position={[-3.57, -0.01, 5.56]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_290_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_290_lambert1_0.material} />
                  </group>
                  <group position={[-0.81, 4.81, 6.7]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_291_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_291_lambert1_0.material} />
                  </group>
                  <group position={[-4.68, 4.22, 5.05]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_292_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_292_lambert1_0.material} />
                  </group>
                  <group position={[-5.52, -0.01, -3.48]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_293_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_293_lambert1_0.material} />
                  </group>
                  <group position={[-0.03, 2.82, -7.01]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_294_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_294_lambert1_0.material} />
                  </group>
                  <group position={[-5.32, 7.14, 0.21]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_295_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_295_lambert1_0.material} />
                  </group>
                  <group position={[5.12, -1.33, -2.61]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_296_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_296_lambert1_0.material} />
                  </group>
                  <group position={[0.43, 8.49, -3.71]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_297_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_297_lambert1_0.material} />
                  </group>
                  <group position={[-1.93, 1.78, 6.57]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_298_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_298_lambert1_0.material} />
                  </group>
                  <group position={[1.06, 6.27, -5.76]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_299_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_299_lambert1_0.material} />
                  </group>
                  <group position={[-1.75, 4.65, 6.31]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_300_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_300_lambert1_0.material} />
                  </group>
                  <group position={[3.31, 7.44, -3.53]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_301_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_301_lambert1_0.material} />
                  </group>
                  <group position={[3.06, 5.64, 5.25]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_302_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_302_lambert1_0.material} />
                  </group>
                  <group position={[-4.57, 3.28, 4.85]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_303_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_303_lambert1_0.material} />
                  </group>
                  <group position={[-3.73, -2.77, 0.3]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_304_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_304_lambert1_0.material} />
                  </group>
                  <group position={[5.41, 2.94, -3.85]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_305_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_305_lambert1_0.material} />
                  </group>
                  <group position={[-3.15, -0.57, 4.77]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_306_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_306_lambert1_0.material} />
                  </group>
                  <group position={[5.02, -0.41, 2.88]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_307_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_307_lambert1_0.material} />
                  </group>
                  <group position={[4, -1.11, 3.48]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_308_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_308_lambert1_0.material} />
                  </group>
                  <group position={[-5.33, 6.23, 1.54]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_309_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_309_lambert1_0.material} />
                  </group>
                  <group position={[3.08, 3.11, 5.73]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_310_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_310_lambert1_0.material} />
                  </group>
                  <group position={[2.22, -2.75, 2.6]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_311_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_311_lambert1_0.material} />
                  </group>
                  <group position={[-0.31, -1.46, -4.9]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_312_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_312_lambert1_0.material} />
                  </group>
                  <group position={[-0.41, -3.42, 1.69]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_313_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_313_lambert1_0.material} />
                  </group>
                  <group position={[-5.76, 4.81, 1.89]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_314_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_314_lambert1_0.material} />
                  </group>
                  <group position={[-5.3, 1.01, 3.12]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_315_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_315_lambert1_0.material} />
                  </group>
                  <group position={[-5.36, -0.52, 0.99]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_316_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_316_lambert1_0.material} />
                  </group>
                  <group position={[-1.2, 8.65, -1.97]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_317_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_317_lambert1_0.material} />
                  </group>
                  <group position={[-2.81, -0.17, -4.62]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_318_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_318_lambert1_0.material} />
                  </group>
                  <group position={[-1.45, 8.58, 1.95]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_319_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_319_lambert1_0.material} />
                  </group>
                  <group position={[4.18, -1.14, -2.02]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_320_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_320_lambert1_0.material} />
                  </group>
                  <group position={[3.34, 6.45, -3.71]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_321_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_321_lambert1_0.material} />
                  </group>
                  <group position={[2.65, -1.4, -3.43]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_322_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_322_lambert1_0.material} />
                  </group>
                  <group position={[-5.7, 5.01, 0.32]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_323_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_323_lambert1_0.material} />
                  </group>
                  <group position={[2.69, 7.81, -2.29]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_324_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_324_lambert1_0.material} />
                  </group>
                  <group position={[-4.56, 4.39, -3.64]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_325_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_325_lambert1_0.material} />
                  </group>
                  <group position={[5.28, 0.07, 0.52]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_326_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_326_lambert1_0.material} />
                  </group>
                  <group position={[-0.89, -1.82, -3.6]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_327_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_327_lambert1_0.material} />
                  </group>
                  <group position={[-4.94, 4.26, -3.02]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_328_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_328_lambert1_0.material} />
                  </group>
                  <group position={[-2.19, 7.52, 2.95]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_329_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_329_lambert1_0.material} />
                  </group>
                  <group position={[-0.25, 8.61, -1.43]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_330_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_330_lambert1_0.material} />
                  </group>
                  <group position={[3.18, -1.61, -2.02]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_331_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_331_lambert1_0.material} />
                  </group>
                  <group position={[1.86, 6.47, 4.23]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_332_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_332_lambert1_0.material} />
                  </group>
                  <group position={[-4.2, 6.41, -1.95]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_333_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_333_lambert1_0.material} />
                  </group>
                  <group position={[3.16, 6.63, 3.05]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_334_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_334_lambert1_0.material} />
                  </group>
                  <group position={[-1.65, 0.5, -4.82]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_335_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_335_lambert1_0.material} />
                  </group>
                  <group position={[3.01, -1.75, 0.53]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_336_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_336_lambert1_0.material} />
                  </group>
                  <group position={[-4.87, 5.76, -0.24]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_337_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_337_lambert1_0.material} />
                  </group>
                  <group position={[-0.86, 2.93, -5.51]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_338_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_338_lambert1_0.material} />
                  </group>
                  <group position={[2.32, 5.73, 4.25]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_339_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_339_lambert1_0.material} />
                  </group>
                  <group position={[2.36, 6.79, -3.29]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_340_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_340_lambert1_0.material} />
                  </group>
                  <group position={[-4.34, 0.46, -2.28]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_341_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_341_lambert1_0.material} />
                  </group>
                  <group position={[1.65, 5.33, -4.67]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_342_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_342_lambert1_0.material} />
                  </group>
                  <group position={[4.82, 4.97, -1.62]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_343_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_343_lambert1_0.material} />
                  </group>
                  <group position={[4.17, 2.12, -3.37]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_344_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_344_lambert1_0.material} />
                  </group>
                  <group position={[-1.9, 4.83, -4.72]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_345_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_345_lambert1_0.material} />
                  </group>
                  <group position={[5.04, 4.74, -0.8]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_346_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_346_lambert1_0.material} />
                  </group>
                  <group position={[0.36, 6.74, -3.83]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_347_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_347_lambert1_0.material} />
                  </group>
                  <group position={[0.35, 6.01, -4.39]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_348_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_348_lambert1_0.material} />
                  </group>
                  <group position={[3.25, 1.69, -3.98]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_349_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_349_lambert1_0.material} />
                  </group>
                  <group position={[4.87, 4.63, -0.78]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_350_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_350_lambert1_0.material} />
                  </group>
                  <group position={[-2.8, 0.03, -3.03]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_351_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_351_lambert1_0.material} />
                  </group>
                  <group position={[-3.22, -0.09, 2.36]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_352_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_352_lambert1_0.material} />
                  </group>
                  <group position={[-1.38, 0.46, -4.12]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_353_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_353_lambert1_0.material} />
                  </group>
                  <group position={[-3.72, 0.51, -2.25]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_354_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_354_lambert1_0.material} />
                  </group>
                  <group position={[2.94, 5.75, -3.09]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_355_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_355_lambert1_0.material} />
                  </group>
                  <group position={[-3.2, 0.28, 2.58]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_356_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_356_lambert1_0.material} />
                  </group>
                  <group position={[4.12, 2.85, 2.77]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_357_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_357_lambert1_0.material} />
                  </group>
                  <group position={[0.69, 1.14, -4.49]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_358_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_358_lambert1_0.material} />
                  </group>
                  <group position={[0.91, 0.7, -4.17]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_359_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_359_lambert1_0.material} />
                  </group>
                  <group position={[1.16, 1.23, 4.37]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_360_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_360_lambert1_0.material} />
                  </group>
                  <group position={[-2.49, -0.51, -2.09]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_361_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_361_lambert1_0.material} />
                  </group>
                  <group position={[-0.7, 2.49, -4.75]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_362_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_362_lambert1_0.material} />
                  </group>
                  <group position={[-3.59, 5.21, -2.4]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_363_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_363_lambert1_0.material} />
                  </group>
                  <group position={[-3.59, 0.2, -1.23]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_364_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_364_lambert1_0.material} />
                  </group>
                  <group position={[2.05, 4.49, -3.95]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_365_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_365_lambert1_0.material} />
                  </group>
                  <group position={[0.23, 3.35, 4.58]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_366_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_366_lambert1_0.material} />
                  </group>
                  <group position={[-3.65, 4.68, 2.31]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_367_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_367_lambert1_0.material} />
                  </group>
                  <group position={[3.31, 5.24, 2.38]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_368_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_368_lambert1_0.material} />
                  </group>
                  <group position={[3.27, 1.21, 2.41]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_369_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_369_lambert1_0.material} />
                  </group>
                  <group position={[1.54, 1.31, 3.77]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_370_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_370_lambert1_0.material} />
                  </group>
                  <group position={[3.56, 5.86, 0.63]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_371_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_371_lambert1_0.material} />
                  </group>
                  <group position={[-4.17, 4.74, 0.14]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_372_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_372_lambert1_0.material} />
                  </group>
                  <group position={[-2.48, -0.14, 1.5]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_373_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_373_lambert1_0.material} />
                  </group>
                  <group position={[-2.91, 0.18, -1.28]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_374_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_374_lambert1_0.material} />
                  </group>
                  <group position={[-2.13, 7.02, 0.17]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_375_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_375_lambert1_0.material} />
                  </group>
                  <group position={[-3.5, 5.04, -1.8]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_376_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_376_lambert1_0.material} />
                  </group>
                  <group position={[2.13, 0.99, -3.03]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_377_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_377_lambert1_0.material} />
                  </group>
                  <group position={[-2.85, 6.38, -0.4]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_378_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_378_lambert1_0.material} />
                  </group>
                  <group position={[0.47, -1.02, -0.43]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_379_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_379_lambert1_0.material} />
                  </group>
                  <group position={[-2.57, 1.07, 2.61]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_380_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_380_lambert1_0.material} />
                  </group>
                  <group name="pDiscShape1_instancer1_381" position={[0.12, 2.46, 3.99]} scale={0.35}>
                    <mesh geometry={nodes.pDiscShape1_instancer1_381_lambert1_0.geometry} material={nodes.pDiscShape1_instancer1_381_lambert1_0.material} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );

}
useGLTF.preload('/explosion/scene.gltf');
