/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jorma Rysky (Joona Venäläinen) (https://sketchfab.com/Rysky)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/timeframe-explosion-9e73437350dc4bcab9b2f3a4a044b16e
title: Timeframe Explosion
*/

import React, { useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/timeframe_explosion/scene.gltf')
  const { actions } = useAnimations(animations, group)


  console.log(actions);
  const [name, setName] = useState("Explosion")

  useFrame(() => {

    let animation = true;
    if (animation) {

      actions[name].play()

      animation = false;
    }

  })



  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group>
            <group name="Object_2" scale={0}>
              <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group>
                  <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.MSAM_Explosion_12_KivikausiMajaMat_KivikausiMajaMat_0.geometry} material={nodes.MSAM_Explosion_12_KivikausiMajaMat_KivikausiMajaMat_0.material} />
                  </group>
                </group>
              </group>
            </group>
            <group scale={0}>
              <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group>
                  <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.MSAM_Explosion_11_KivikausiMajaMat_KivikausiMajaMat_0.geometry} material={nodes.MSAM_Explosion_11_KivikausiMajaMat_KivikausiMajaMat_0.material} />
                  </group>
                </group>
              </group>
            </group>
            <group scale={0}>
              <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group>
                  <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.MSAM_Explosion_10_KivikausiMajaMat_KivikausiMajaMat_0.geometry} material={nodes.MSAM_Explosion_10_KivikausiMajaMat_KivikausiMajaMat_0.material} />
                  </group>
                </group>
              </group>
            </group>
            <group scale={0}>
              <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group>
                  <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.MSAM_Explosion_9_KivikausiMajaMat_KivikausiMajaMat_0.geometry} material={nodes.MSAM_Explosion_9_KivikausiMajaMat_KivikausiMajaMat_0.material} />
                  </group>
                </group>
              </group>
            </group>
            <group scale={0}>
              <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group>
                  <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.MSAM_Explosion_8_KivikausiMajaMat_KivikausiMajaMat_0.geometry} material={nodes.MSAM_Explosion_8_KivikausiMajaMat_KivikausiMajaMat_0.material} />
                  </group>
                </group>
              </group>
            </group>
            <group scale={0}>
              <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group>
                  <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.MSAM_Explosion_7_KivikausiMajaMat_KivikausiMajaMat_0.geometry} material={nodes.MSAM_Explosion_7_KivikausiMajaMat_KivikausiMajaMat_0.material} />
                  </group>
                </group>
              </group>
            </group>
            <group scale={0}>
              <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group>
                  <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.MSAM_Explosion_6_KivikausiMajaMat_KivikausiMajaMat_0.geometry} material={nodes.MSAM_Explosion_6_KivikausiMajaMat_KivikausiMajaMat_0.material} />
                  </group>
                </group>
              </group>
            </group>
            <group scale={0}>
              <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group>
                  <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.MSAM_Explosion_5_KivikausiMajaMat_KivikausiMajaMat_0.geometry} material={nodes.MSAM_Explosion_5_KivikausiMajaMat_KivikausiMajaMat_0.material} />
                  </group>
                </group>
              </group>
            </group>
            <group scale={0}>
              <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group>
                  <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.MSAM_Explosion_4_KivikausiMajaMat_KivikausiMajaMat_0.geometry} material={nodes.MSAM_Explosion_4_KivikausiMajaMat_KivikausiMajaMat_0.material} />
                  </group>
                </group>
              </group>
            </group>
            <group scale={0}>
              <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group>
                  <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.MSAM_Explosion_3_KivikausiMajaMat_KivikausiMajaMat_0.geometry} material={nodes.MSAM_Explosion_3_KivikausiMajaMat_KivikausiMajaMat_0.material} />
                  </group>
                </group>
              </group>
            </group>
            <group scale={0}>
              <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group>
                  <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.MSAM_Explosion_2_KivikausiMajaMat_KivikausiMajaMat_0.geometry} material={nodes.MSAM_Explosion_2_KivikausiMajaMat_KivikausiMajaMat_0.material} />
                  </group>
                </group>
              </group>
            </group>
            <group>
              <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group>
                  <group position={[-7.05, -14.16, 0.31]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh geometry={nodes.MSAM_Explosion_1_KivikausiMajaMat_KivikausiMajaMat_0.geometry} material={nodes.MSAM_Explosion_1_KivikausiMajaMat_KivikausiMajaMat_0.material} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/timeframe_explosion/scene.gltf')
