/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Artbake Graphics (https://sketchfab.com/ismir)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mountain-a45e579a7d754a1dbf40cdc5cdfe508a
title: Mountain
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mountain/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.gray} />
        <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials.green} />
      </group>
    </group>
  )
}

useGLTF.preload('/mountain/scene.gltf')
