/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Anskar (https://sketchfab.com/Anskar)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-mushrooms-amanita-muscaria-7d2639b6527f4bd4b1a063dabe6afe88
title: Low Poly Mushrooms Amanita Muscaria
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mushrooms/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-50.75, 0, 0.11]} rotation={[-1.71, -0.19, 0.23]} scale={1.09}>
            <mesh   geometry={nodes.Icosphere006_Mushroom_White_0.geometry} material={nodes.Icosphere006_Mushroom_White_0.material} />
            <mesh   geometry={nodes.Icosphere006_Mushroom_Yellow_0.geometry} material={nodes.Icosphere006_Mushroom_Yellow_0.material} />
            <mesh   geometry={nodes.Icosphere006_Mushroom_Red_0.geometry} material={nodes.Icosphere006_Mushroom_Red_0.material} />
          </group>
          <group position={[36.56, -6.09, 0.11]} rotation={[-Math.PI / 2, 0, -3]} scale={3.13}>
            <mesh   geometry={nodes.Circle002_Mushroom_Yellow_0.geometry} material={nodes.Circle002_Mushroom_Yellow_0.material} />
            <mesh   geometry={nodes.Circle002_Mushroom_Red_0.geometry} material={nodes.Circle002_Mushroom_Red_0.material} />
            <mesh   geometry={nodes.Circle002_Mushroom_White_0.geometry} material={nodes.Circle002_Mushroom_White_0.material} />
          </group>
          <group position={[-2.75, 0.26, 0.11]} rotation={[-Math.PI / 2, 0, -0.2]} scale={[5.73, 5.73, 5.39]}>
            <mesh   geometry={nodes.Circle_Mushroom_Yellow_0.geometry} material={nodes.Circle_Mushroom_Yellow_0.material} />
            <mesh   geometry={nodes.Circle_Mushroom_Red_0.geometry} material={nodes.Circle_Mushroom_Red_0.material} />
            <mesh   geometry={nodes.Circle_Mushroom_White_0.geometry} material={nodes.Circle_Mushroom_White_0.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mushrooms/scene.gltf')
