/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Bull studios (https://sketchfab.com/dzemalmclaren)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/stylized-lowpoly-rock-6e476441b5614231bf4e8de194c418d9
title: Stylized lowpoly rock
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/rock/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.02, -0.01, 0.24]} rotation={[3.01, 0.27, -0.23]} scale={0.33}>
            <mesh   geometry={nodes.node_id4_Material_52_0.geometry} material={materials.Material_52} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rock/scene.gltf')
